ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'REFUND_FAILED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'WAITLIST_NOTIFIED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'WAITLIST_EXPIRED';
